spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false

# file releated all configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  media: media/