spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true

# file releated all configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# project:
#   image:
#     product: image/